/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R3dTabiatRouteImport } from './routes/3d-tabiat'
import { Route as QizilKitobRouteImport } from './routes/qizil-kitob'
import { Route as VideolarRouteImport } from './routes/videolar'
import { Route as SinfGradeRouteImport } from './routes/sinf.$grade'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R3dTabiatRoute = R3dTabiatRouteImport.update({
  id: '/3d-tabiat',
  path: '/3d-tabiat',
  getParentRoute: () => rootRouteImport,
} as any)
const QizilKitobRoute = QizilKitobRouteImport.update({
  id: '/qizil-kitob',
  path: '/qizil-kitob',
  getParentRoute: () => rootRouteImport,
} as any)
const VideolarRoute = VideolarRouteImport.update({
  id: '/videolar',
  path: '/videolar',
  getParentRoute: () => rootRouteImport,
} as any)
const SinfGradeRoute = SinfGradeRouteImport.update({
  id: '/sinf/$grade',
  path: '/sinf/$grade',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/3d-tabiat': typeof R3dTabiatRoute
  '/qizil-kitob': typeof QizilKitobRoute
  '/videolar': typeof VideolarRoute
  '/sinf/$grade': typeof SinfGradeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/3d-tabiat': typeof R3dTabiatRoute
  '/qizil-kitob': typeof QizilKitobRoute
  '/videolar': typeof VideolarRoute
  '/sinf/$grade': typeof SinfGradeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/3d-tabiat': typeof R3dTabiatRoute
  '/qizil-kitob': typeof QizilKitobRoute
  '/videolar': typeof VideolarRoute
  '/sinf/$grade': typeof SinfGradeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/3d-tabiat' | '/qizil-kitob' | '/videolar' | '/sinf/$grade'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/3d-tabiat' | '/qizil-kitob' | '/videolar' | '/sinf/$grade'
  id:
    | '__root__'
    | '/'
    | '/3d-tabiat'
    | '/qizil-kitob'
    | '/videolar'
    | '/sinf/$grade'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R3dTabiatRoute: typeof R3dTabiatRoute
  QizilKitobRoute: typeof QizilKitobRoute
  VideolarRoute: typeof VideolarRoute
  SinfGradeRoute: typeof SinfGradeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/3d-tabiat': {
      id: '/3d-tabiat'
      path: '/3d-tabiat'
      fullPath: '/3d-tabiat'
      preLoaderRoute: typeof R3dTabiatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qizil-kitob': {
      id: '/qizil-kitob'
      path: '/qizil-kitob'
      fullPath: '/qizil-kitob'
      preLoaderRoute: typeof QizilKitobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videolar': {
      id: '/videolar'
      path: '/videolar'
      fullPath: '/videolar'
      preLoaderRoute: typeof VideolarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sinf/$grade': {
      id: '/sinf/$grade'
      path: '/sinf/$grade'
      fullPath: '/sinf/$grade'
      preLoaderRoute: typeof SinfGradeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R3dTabiatRoute: R3dTabiatRoute,
  QizilKitobRoute: QizilKitobRoute,
  VideolarRoute: VideolarRoute,
  SinfGradeRoute: SinfGradeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
